paramount_mga_requirements = {
    "enterprise": "Paramount MGA",
    "coverages": ["AL", "APD", "MTC"],
    "international_drivers": True,
    "cdl_no_state": True,
    "min_year_exp": 2,
    "max_driver_age": 70,
    "min_driver_age": 23,
    "max_minor_violations": 2,
    "max_major_violations": 1,
    "max_accidents": 1,
    "iss_score_limit": 0.85,
    "vehicle_age_limit": 20,
    "vehicle_type": "Truck tractor",
    "loss_ratio_limit": 0.50,
    "new_busines": True,
    "uiia": True,
    "iftas_required": True,
}
